### PR TITLE
Fix startup crash

### PR DESCRIPTION
**Pull request by LGhassen**
This fixes te applciation not starting on some systems due to a parsing issue.

More info here: https://stackoverflow.com/questions/19049906/input-string-was-not-in-a-correct-format-in-double-parse

### CODE REVIEW

**Comment by dhlevi** [comment]
Wow, dusting off some ancient code! Looks fine to me though, I'll merge it in and see if I can get a build done to update the executable... I'm glad someone found a use for this!

**Comment by LGhassen** [comment]
@dhlevi gui-based noise/libnoise editors with support for equirectangular output seem to be very few.

I found another issue yesterday after making a new build, the output generated by the preview/save window seems to be messed up, while the small preview in bottom left works. I didn't have time to investigate but the values coming out of the noisefactory seem to be 1000x higher than they need to be so everything is pure white or black in the image. No worries if you have no idea though since this is an old project

**Comment by dhlevi** [comment]
@LGhassen I just pushed up some changes from an apparently updated (but still somewhat old) branch I had. The Preview window appears to be working as expected (terrible UI not withstanding...), but I'll poke around a bit and see if I can spot some corner cases... there are some definite improvements that could be done, and apparently I was working on a load features at some point five years ago that I might see if I can get into shape and post up as well.

Changes are in a new branch (https://github.com/dhlevi/LibnoiseDesigner/tree/version-update) until I'm sure it's all working OK (there was some folder structure changes and such I want to make sure are OK)

**Comment by LGhassen** [comment]
Thanks, I just tested it and the preview view is still broken for me. It looks like this https://i.imgur.com/Fld7Y2n.png you can see that the small preview in the corner works fine though.

It must be a platform thing again, I will try and debug it next time since I reproduce the issue.

**Pull request merged**
